services:
    api:
        container_name: mida-sync
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'curl', '-sf', 'http://localhost:3000/health']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
